name: icon_pack
description: meta icon pack with picker
version: 0.0.1
homepage: https://github.com/udshu/IconPack

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: any
  provider: any
  cupertino_icons: any
  line_icons: any
  font_awesome_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

